### ISSUE TITLE
Angel's Feedback on Content

### ISSUE THREAD

**Issue by Angelqijiadeng** [asibole1/Project#1]
Hi Alicia, your website is pretty good in decoration, and has many useful contents. 
Here are two suggestions on content:
1. You can put breakfast, lunch, dinner, and snacks in a drop down menu on receipts. It will be easier for users to access the receipts they want. 
2. If you have a video of your cooking, you can put in your homepage or any other pages if you like. It will also attract your web page visitors.

**Comment by asibole1** [comment]
Thank you for these suggestions, Angel! I love the first one and it'd take a little more time than I had left for this version since I'd have to make sub-pages for each category, but I'd definitely do this in a V3. 

And I love putting a video! I am not that talented with video editing but I bet I could whip something up even more tiktok style or something with a voiceover. Great suggestion!
